env:
  browser: true
  commonjs: true
  node: true
  jquery: true
  jasmine: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
